version: '3'
services:
  my-app:
    image: chlav/havryliuk-test-clear-solution:latest
    ports:
      - 8080:8080
    links:
      - ps-db
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://ps-db/users
      - MYAPP_JDBC_USER=admin
      - MYAPP_JDBC_PASS=admin
  ps-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - 5432:5432