version: '3'
services:
  my-app:
    image: chlav/havryliuk-test-clear-solution:latest
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://app-db:5432/users
      - MYAPP_JDBC_USER=admin
      - MYAPP_JDBC_PASS=admin
  ps-db:
    image: postgres
    restart: always
    hostname: ps-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - 5432:5432
#    volumes:
#      - /opt/postgresdata/:/var/lib/postgresql/users