version: '1.0'
#
#services:
#
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: users
#    ports:
#      - 5432:5432
#
#version: '2'

services:
  app:
    build: .
    image: chlav/havryliuk-test-clear-solution:latest
    ports:
      - 8080:8080
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
    container_name: havryliuk-test-clear-solution
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
#    volumes:
#      - ./storage/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
      PG_TRUST_LOCALNET: true
      PGHOST: localhost
    container_name: havryliuk-test-clear-solution