springdoc:
  api-docs:
    enabled: true
    path: /api-docs
---
spring:
  application:
    name: havryliuk-test-clear-solution
#  datasource:
#    url: jdbc:postgresql://localhost:5432/users
#    username: admin
#    password: admin
  jpa:
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
---
constants:
  allowed-age-to-register: 18
---
#server:
#  title:
#    include-detail: on_param