springdoc:
  api-docs:
    enabled: true
    path: /api-docs

spring:
  profiles:
    active: localhost
---

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: admin
  config:
    activate:
      on-profile: localhost

---
spring:
  datasource:
    url: jdbc:postgresql://ps-db
#    url: jdbc:postgresql://ps-db:5432/users
    username: admin
    password: admin
  config:
    activate:
      on-profile: dev

---
spring:
  application:
    name: havryliuk-test-clear-solution
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  config:
    activate:
      on-profile: used-always-in-all-profiles

---
constants:
  allowed-age-to-register: 18
